import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <nav className="w-1/2 h-screen">
          <ul className="bg-yellow-500 flex flex-col justify-center items-center w-100 h-screen text-6xl font-black">
            <li>
              <h1>Introduction</h1>
            </li>
            <li>
              <h1>Skills</h1>
            </li>
            <li>
              <h1>Experience</h1>
            </li>
            <li>
              <h1>Showcase</h1>
            </li>
            <li>
              <h1>Contact</h1>
            </li>
          </ul>
        </nav>
      </main>
    </div>
  )
}

export default Home
